-- CreateTable
CREATE TABLE "Language" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "language" STRING NOT NULL,

    CONSTRAINT "Language_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Framework" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "framework" STRING NOT NULL,
    "languageId" INT4 NOT NULL,

    CONSTRAINT "Framework_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Framework" ADD CONSTRAINT "Framework_languageId_fkey" FOREIGN KEY ("languageId") REFERENCES "Language"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
