-- CreateTable
CREATE TABLE "Language" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "language" STRING NOT NULL,

    CONSTRAINT "Language_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BaseImage" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" STRING NOT NULL,
    "languageId" INT4 NOT NULL,

    CONSTRAINT "BaseImage_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "BaseImage" ADD CONSTRAINT "BaseImage_languageId_fkey" FOREIGN KEY ("languageId") REFERENCES "Language"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
